name: Build and Release PDFs

on:
  push:
    branches:
      - main

jobs:
  build-and-release-pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build PDFs
      uses: xu-cheng/latex-action@v3
      with:
        root_file: |
          statistics.tex
          probability.tex
          ml.tex

    - name: Create Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.pdf"
        tags: false
        draft: false
